spring:
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/loandb
        username: root
        password: rps@123
        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
    level:
        root: INFO

# Application properties
luma:
    app:
        jwt-secret: bc54dac40d2a7d2c54c111c9dfe404a75c5a3ddf0e981c4c4e8dec6fa86974d6
        accessExpirationTime: 600000
        refreshExpirationTime: 3600000
        superuserEmail: ashutoshshrm529@gmail.com
        superuserPassword: Password123*